import {readFileSync,writeFileSync} from 'node:fs';

let s=readFileSync('./bootstrap2.js','utf8');

// Preserve stable human labels for current multi-area groups and attach verified locality codes.
s=s.replace("if(mapGroups.arsos){mapGroups.arsos.isAreaGroup=true;mapGroups.arsos.district='Λεμεσός';mapGroups.arsos.community='Άρσος';}","if(mapGroups.arsos){mapGroups.arsos.isAreaGroup=true;mapGroups.arsos.district='Λεμεσός';mapGroups.arsos.community='Άρσος';}\nfor(const p of Object.values(properties)){if(p.areaKey==='arsos')p.vilCode=322;else if(p.areaKey==='pafos')p.vilCode=218;else if(p.areaKey==='pentakomo')p.vilCode=126;}\n");
s=s.replace("for(const [key,g] of Object.entries(mapGroups))if(g?.isAreaGroup)g.title=(g.community||key)+' — Ιδιόκτητα & προς αγορά';","if(mapGroups.limassol){mapGroups.limassol.district='Λεμεσός';mapGroups.limassol.community='Λεμεσός';}\nif(mapGroups.pentakomo){mapGroups.pentakomo.district='Λεμεσός';mapGroups.pentakomo.community='Πεντάκωμο';}\nfor(const [key,g] of Object.entries(mapGroups))if(g?.isAreaGroup)g.title=(g.community||key)+' — Ιδιόκτητα & προς αγορά';");

// Exact-property query: use district when known and verified VIL_CODE when present; unknown districts may still resolve if globally unique.
s=s.replace("for(const p of loc){const dist=districtCode(p);if(!dist)continue;const q=x=>String(x).replaceAll(\"'\",\"''\");clauses.push(\"(DIST_CODE=\"+dist+\" AND SHEET='\"+q(p.sheet)+\"' AND PLAN_NBR='\"+q(p.plan)+\"' AND BLCK_CODE=\"+Number(p.block)+\" AND PARCEL_NBR=\"+Number(p.parcel)+\")\");}","for(const p of loc){const dist=districtCode(p);const q=x=>String(x).replaceAll(\"'\",\"''\");let clause=\"SHEET='\"+q(p.sheet)+\"' AND PLAN_NBR='\"+q(p.plan)+\"' AND BLCK_CODE=\"+Number(p.block)+\" AND PARCEL_NBR=\"+Number(p.parcel);if(dist)clause=\"DIST_CODE=\"+dist+\" AND \"+clause;if(p.vilCode!=null)clause+=(\" AND VIL_CODE=\"+Number(p.vilCode));clauses.push(\"(\"+clause+\")\");}");

// Never choose the first feature when an exact cadastral tuple is ambiguous; dedupe repeated OBJECTIDs first and use no loose fallback.
s=s.replace("writeFileSync('./server.js',c,'utf8');","c=replaceOnce(c,\"function safeFeature(fs,p){const exact=exactFeature(fs,p);if(exact)return exact;const loose=(fs||[]).filter(f=>{const a=f.attributes||{};return Number(a.BLCK_CODE)===Number(p.block)&&Number(a.PARCEL_NBR)===Number(p.parcel);});if(loose.length===1){console.warn(`PARCEL_LOOSE_MATCH ${p.code||p.title||p.parcel}`);return loose[0];}return null;}\",\"function safeFeature(fs,p){let exact=(fs||[]).filter(f=>{const a=f.attributes||{};return Number(a.BLCK_CODE)===Number(p.block)&&Number(a.PARCEL_NBR)===Number(p.parcel)&&norm(a.SHEET)===norm(p.sheet)&&norm(a.PLAN_NBR)===norm(p.plan);});if(p.vilCode!=null)exact=exact.filter(f=>Number(f.attributes?.VIL_CODE)===Number(p.vilCode));const seen=new Set();exact=exact.filter(f=>{const id=String(f.attributes?.OBJECTID??f.attributes?.SBPI_ID_NO??JSON.stringify(f.attributes||{}));if(seen.has(id))return false;seen.add(id);return true;});if(exact.length===1)return exact[0];if(exact.length>1)console.warn(`PARCEL_AMBIGUOUS ${p.code||p.title||p.parcel}: ${exact.length} exact matches`);return null;}\",'strict unique parcel matching');\nwriteFileSync('./server.js',c,'utf8');");

// Property detail page and central catalogue expose registry intake date. Existing records remain blank unless verified.
s=s.replace("writeFileSync('./viewer.js',v,'utf8');",`v=v.replace("\${field('Αριθμός τεμαχίου',p.parcel)}","\${field('Φύλλο',p.sheet)}\${field('Σχέδιο',p.plan)}\${field('Μπλοκ',p.block)}\${field('Αριθμός τεμαχίου',p.parcel)}\${field('DLS VIL_CODE',p.vilCode)}\${field('Ημερομηνία καταχώρησης',p.dateAdded)}");
v=v.replace("const headers=[['Κωδικός','text'],['Όνομα','text'],['Τύπος','text'],['Εγγραφή','text'],['Επαρχία','text'],['Δήμος/Κοινότητα','text'],['Ενορία','text'],['Εμβαδόν','number'],['Μερίδιο','text'],['Ζώνη','text'],['Τιμή','number'],['Links','text']];","const headers=[['Κωδικός','text'],['Όνομα','text'],['Τύπος','text'],['Ημ/νία καταχώρησης','text'],['Εγγραφή','text'],['Επαρχία','text'],['Δήμος/Κοινότητα','text'],['Ενορία','text'],['Εμβαδόν','number'],['Μερίδιο','text'],['Ζώνη','text'],['Τιμή','number'],['Links','text']];");
v=v.replace("<td data-sort=\\"\${esc(type)}\\">\${type}</td><td data-sort=\\"\${esc(registration)}\\">","<td data-sort=\\"\${esc(type)}\\">\${type}</td><td data-sort=\\"\${esc(p.dateAdded||'')}\\" data-added=\\"\${esc(p.dateAdded||'')}\\" data-kind=\\"\${esc(p.kind)}\\">\${esc(p.kind==='candidate'?(p.dateAdded||'—'):'—')}</td><td data-sort=\\"\${esc(registration)}\\">");
v=v.replace("<div class=\\"wrap\\"><h1>ΟΛΑ ΤΑ ΑΚΙΝΗΤΑ</h1><table class=\\"table\\" id=\\"allPropertiesTable\\">","<div class=\\"wrap\\"><h1>ΟΛΑ ΤΑ ΑΚΙΝΗΤΑ</h1><div style=\\"display:flex;gap:10px;align-items:center;margin:0 0 14px;flex-wrap:wrap\\"><strong>ΠΡΟΣ ΑΓΟΡΑ — ΚΑΤΑΧΩΡΗΣΗ:</strong><select id=\\"catalogDateFilter\\" style=\\"padding:7px 9px\\"><option value=\\"all\\">Όλα</option><option value=\\"today\\">Σήμερα</option><option value=\\"7\\">Τελευταίες 7 ημέρες</option><option value=\\"30\\">Τελευταίες 30 ημέρες</option><option value=\\"undated\\">Χωρίς ημερομηνία</option></select><button id=\\"catalogDateClear\\" type=\\"button\\" style=\\"padding:7px 10px\\">Καθαρισμός</button></div><table class=\\"table\\" id=\\"allPropertiesTable\\">");
v=v.replace("buttons.forEach(btn=>btn.addEventListener('click',()=>{","const dateFilter=document.getElementById('catalogDateFilter'),dateClear=document.getElementById('catalogDateClear');const applyDateFilter=()=>{const f=dateFilter?.value||'all',today=new Date();today.setHours(0,0,0,0);Array.from(tbody.querySelectorAll('tr')).forEach(r=>{const cell=r.children[3],kind=cell?.dataset.kind||'',raw=cell?.dataset.added||'',d=raw?new Date(raw+'T00:00:00'):null;let show=true;if(f!=='all'){if(kind!=='candidate')show=false;else if(f==='today')show=!!d&&d.getTime()===today.getTime();else if(f==='7'||f==='30'){if(!d)show=false;else{const days=(today-d)/86400000;show=days>=0&&days<Number(f);}}else if(f==='undated')show=!d;}r.style.display=show?'':'none';});};dateFilter?.addEventListener('change',applyDateFilter);dateClear?.addEventListener('click',()=>{if(dateFilter)dateFilter.value='all';applyDateFilter();});buttons.forEach(btn=>btn.addEventListener('click',()=>{");
writeFileSync('./viewer.js',v,'utf8');`);

// Keep DLS URLs small by batching unique exact-property clauses and dedupe returned OBJECTIDs across chunks.
const from=`  const where=clauses.join(' OR ');
  const j=await query(PARCELS,{f:'json',where,outFields:'SBPI_ID_NO,DIST_CODE,VIL_CODE,BLCK_CODE,PARCEL_NBR,SHEET,PLAN_NBR,OBJECTID,SHAPE.STArea()',returnGeometry:true,outSR:CRS,returnZ:false,resultRecordCount:1000},2,10000);
  return j.features||[];`;
const to=`  const all=[],seen=new Set(),uniqueClauses=[...new Set(clauses)];
  for(let i=0;i<uniqueClauses.length;i+=4){
    const where=uniqueClauses.slice(i,i+4).join(' OR ');
    const j=await query(PARCELS,{f:'json',where,outFields:'SBPI_ID_NO,DIST_CODE,VIL_CODE,BLCK_CODE,PARCEL_NBR,SHEET,PLAN_NBR,OBJECTID,SHAPE.STArea()',returnGeometry:true,outSR:CRS,returnZ:false,resultRecordCount:1000},2,10000);
    for(const f of (j.features||[])){const id=String(f.attributes?.OBJECTID??f.attributes?.SBPI_ID_NO??JSON.stringify(f.attributes||{}));if(seen.has(id))continue;seen.add(id);all.push(f);}
  }
  return all;`;
if(!s.includes(from))throw new Error('bootstrap3 patch not found: exact DLS batch query');
s=s.replace(from,to);
writeFileSync('./bootstrap2.runtime.js',s,'utf8');
await import('./bootstrap2.runtime.js?chunked='+Date.now());
import('./audit-runtime.js?audit='+Date.now()).catch(e=>console.error('GIS_AUDIT_IMPORT_FAIL '+(e?.stack||e)));
import('./smoke-runtime.js?smoke='+Date.now()).catch(e=>console.error('RUNTIME_SMOKE_IMPORT_FAIL '+(e?.stack||e)));
