export const properties = {
  // OWNED — ARSOS
  IDI0001:{code:'ΕΡΓ-ΙΔΙ-0001',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Μέσα στο χωριό',registration:'99/25',share:'1/2',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'5322V01',block:1,parcel:262,registeredArea:0,zone:'Η1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — γωνιακό/προνομιακό',sourceUrl:null,notes:'Ερειπωμένη κατοικία'},
  IDI0002:{code:'ΕΡΓ-ΙΔΙ-0002',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΣΤΑΥΡΟΣ',registration:'4/30',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'40W2',block:4,parcel:32,registeredArea:12622,zone:'Η6',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null},
  IDI0003:{code:'ΕΡΓ-ΙΔΙ-0003',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΚΟΙΛΙΑΡΟΥ',registration:'5/120',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'40W2',block:5,parcel:120,registeredArea:13981,zone:'Ζ1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΧΩΜΑΤΟΔΡΟΜΟΣ — από πρόσοψη και πίσω',sourceUrl:null},
  IDI0004:{code:'ΕΡΓ-ΙΔΙ-0004',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΒΑΛΑΝΤΟΣ',registration:'5/122',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'40W2',block:5,parcel:122,registeredArea:4822,zone:'Η6α',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null},
  IDI0005:{code:'ΕΡΓ-ΙΔΙ-0005',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΚΟΚΚΙΝΟΚΑΜΠΟΣ',registration:'2/124',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'31E1',block:2,parcel:124,registeredArea:17660,zone:'Ζ1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null},
  IDI0006:{code:'ΕΡΓ-ΙΔΙ-0006',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΣΤΑΖΟΥΣΑ Αμπέλι',registration:'4/274',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'48W1',block:4,parcel:287,registeredArea:15581,zone:'Ζ1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null},
  IDI0007:{code:'ΕΡΓ-ΙΔΙ-0007',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΒΥΖΑΤΖΙΑ',registration:'3/286',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'47E1',block:3,parcel:296,registeredArea:7479,zone:'Ζ1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null},
  IDI0008:{code:'ΕΡΓ-ΙΔΙ-0008',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΚΑΜΙΝΟΥΔΙΑ',registration:'0/7638',share:'100%',district:'Πάφος',community:'Άγιος Νικόλαος Πάφου',areaKey:'pafos',vilCode:218,sheet:'46',plan:'24',block:0,parcel:260,registeredArea:7358,zone:null,roadAccess:'ΠΕΡΙΚΛΕΙΣΤΟ — καμία σχέση με δρόμο',sourceUrl:null},
  IDI0009:{code:'ΕΡΓ-ΙΔΙ-0009',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΦΡΑΚΤΗ Κοντά στο χωριό',registration:'0/7732',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'40',block:0,parcel:434,registeredArea:1673,zone:'Η2',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null},
  IDI0010:{code:'ΕΡΓ-ΙΔΙ-0010',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΓΟΥΠΠΟΣ',registration:'0/8225',share:'100%',district:'Πάφος',community:'Άγιος Νικόλαος Πάφου',areaKey:'pafos',vilCode:218,sheet:'46',plan:'24',block:0,parcel:575,registeredArea:14382,zone:null,roadAccess:'ΠΕΡΙΚΛΕΙΣΤΟ — καμία σχέση με δρόμο',sourceUrl:null},
  IDI0011:{code:'ΕΡΓ-ΙΔΙ-0011',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΦΟΥΡΝΟΣ Μέσα στο χωριό',registration:'0/9564',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'5322V01',block:1,parcel:301,registeredArea:0,zone:'Η1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null},
  IDI0012:{code:'ΕΡΓ-ΙΔΙ-0012',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΑΓΙΟΣ ΓΕΩΡΓΙΟΣ',registration:'0/10226',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'47',block:0,parcel:470,registeredArea:261,zone:'Γ3',roadAccess:'ΠΕΡΙΚΛΕΙΣΤΟ — καμία σχέση με δρόμο',sourceUrl:null},
  IDI0013:{code:'ΕΡΓ-ΙΔΙ-0013',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΣΠΙΤΙ Μέσα στο χωριό',registration:'0/10436',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'5322V01',block:1,parcel:912,registeredArea:168,zone:'Η1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null,notes:'Διώροφη κατοικία 1940, κατηγορία Β, πλήρης ανακαίνιση 1980'},
  IDI0014:{code:'ΕΡΓ-ΙΔΙ-0014',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΑΓ. ΓΙΩΡΚΗΣ',registration:'0/10488',share:'1/2',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'47',block:0,parcel:91,registeredArea:7358,zone:'Γ3',roadAccess:'ΠΕΡΙΚΛΕΙΣΤΟ — καμία σχέση με δρόμο',sourceUrl:null},
  IDI0015:{code:'ΕΡΓ-ΙΔΙ-0015',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΚΑΖΑΝΙΑ Μέσα στο χωριό',registration:'0/11338',share:'100%',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'5322V01',block:1,parcel:827,registeredArea:177,zone:'Η1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null,notes:'Ερειπωμένη κατοικία'},
  IDI0016:{code:'ΕΡΓ-ΙΔΙ-0016',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΜΙΛΟΝΗΣ',registration:'0/12110',share:'1/2',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'40',block:0,parcel:743,registeredArea:3679,zone:'Η4',roadAccess:'ΠΕΡΙΚΛΕΙΣΤΟ — καμία σχέση με δρόμο',sourceUrl:null},
  IDI0017:{code:'ΕΡΓ-ΙΔΙ-0017',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'ΚΟΥΤΖΙΕΝΑ Χώρος Στάθμευσης Μέσα στο χωριό',registration:'0/12563',share:'2/3',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'5322V01',block:1,parcel:832,registeredArea:64,zone:'Η1',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — από μία πλευρά (πρόσοψη)',sourceUrl:null},

  // OWNED — OTHER AREAS / UNITS
  IDI0018:{code:'ΕΡΓ-ΙΔΙ-0018',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Πανθέα Σπίτι',registration:'9/157',share:'100%',district:'Λεμεσός',community:'Λεμεσός, Μέσα Γειτονιά',parish:'Πανθέα',areaKey:'limassol',vilCode:11,sheet:'54',plan:'420203',block:9,parcel:158,registeredArea:525,zone:null,roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ',sourceUrl:null,notes:'Locator corrected 2026-10-02 from original plan + unique DLS match. Prior 54/500304 block 3 was a different real parcel and is retained only as correction history.'},
  IDI0019:{code:'ΕΡΓ-ΙΔΙ-0019',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Pieris Court Διαμέρισμα 16',registration:'1/49385',share:'100%',district:'Λεμεσός',community:'Λεμεσός',areaKey:'limassol',vilCode:0,sheet:'54',plan:'580601',block:1,parcel:909,parentRegistration:'1/44475',parentArea:1457,registeredArea:null,zone:null,roadAccess:null,sourceUrl:null,notes:'Το διαθέσιμο αρχείο δεν συνδέει με ασφάλεια συγκεκριμένο εμβαδό μονάδας με τον αριθμό εγγραφής.'},
  IDI0020:{code:'ΕΡΓ-ΙΔΙ-0020',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Πεντάδρομος Γραφείο 504',registration:'5/58821',share:'100%',district:'Λεμεσός',community:'Λεμεσός',areaKey:'limassol',vilCode:0,sheet:'54',plan:'580502',block:5,parcel:485,parentRegistration:'5/34673',parentArea:3200,unitArea:120,zone:null,roadAccess:null,sourceUrl:null},
  IDI0021:{code:'ΕΡΓ-ΙΔΙ-0021',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Κουμανδαρίας Γραφεία',registration:'3/39327',share:'100%',district:'Λεμεσός',community:'Λεμεσός',areaKey:'limassol',vilCode:0,sheet:'59',plan:'020202',block:3,parcel:658,registeredArea:118,zone:'Πα6',roadAccess:'ΕΓΓΕΓΡΑΜΜΕΝΟΣ ΔΡΟΜΟΣ — γωνιακό/προνομιακό',sourceUrl:null},
  IDI0022:{code:'ΕΡΓ-ΙΔΙ-0022',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Governors Χωράφι Μικρό',registration:'0/14734',share:'100%',district:'Λεμεσός',community:'Πεντάκωμο',areaKey:'pentakomo',vilCode:126,sheet:'55',plan:'35',block:0,parcel:377,registeredArea:1542,zone:'Η7',seaDistance:398.66,sourceUrl:null,roadAccess:'ΔΙΚΑΙΩΜΑ ΔΙΑΒΑΣΗΣ — καμία σχέση με δρόμο'},
  IDI0023:{code:'ΕΡΓ-ΙΔΙ-0023',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Governors Χωράφι Μεγάλο',registration:'0/15624',share:'100%',district:'Λεμεσός',community:'Πεντάκωμο',areaKey:'pentakomo',vilCode:126,sheet:'55',plan:'35',block:0,parcel:315,registeredArea:6277,zone:'Η7',sourceUrl:null,roadAccess:'ΠΕΡΙΚΛΕΙΣΤΟ — καμία σχέση με δρόμο'},
  IDI0024:{code:'ΕΡΓ-ΙΔΙ-0024',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Pieris Court Διαμέρισμα 30',registration:'1/49395',share:'100%',district:'Λεμεσός',community:'Λεμεσός',areaKey:'limassol',vilCode:0,sheet:'54',plan:'580601',block:1,parcel:909,parentRegistration:'1/44475',parentArea:1457,registeredArea:null,zone:null,roadAccess:null,sourceUrl:null,notes:'Το διαθέσιμο αρχείο δεν συνδέει με ασφάλεια συγκεκριμένο εμβαδό μονάδας με τον αριθμό εγγραφής.'},
  IDI0025:{code:'ΕΡΓ-ΙΔΙ-0025',kind:'owned',status:'ΙΔΙΟΚΤΗΣΙΑ',title:'Πεντάδρομος Γραφείο 504Α',registration:'5/58822',share:'100%',district:'Λεμεσός',community:'Λεμεσός',areaKey:'limassol',vilCode:0,sheet:'54',plan:'580502',block:5,parcel:485,parentRegistration:'5/34673',parentArea:3200,unitArea:44,zone:null,roadAccess:null,sourceUrl:null},

  // PURCHASE CANDIDATES
  AKI0001:{code:'ΕΡΓ-ΑΚΙ-0001',kind:'candidate',status:'ΠΑΡΕΛΘΩΝ ΠΛΕΙΣΤΗΡΙΑΣΜΟΣ',title:'Αγία Τριάδα Λεμεσού — κατοικία',registration:'1/44993',district:'Λεμεσός',community:'Αγία Τριάδα',areaKey:'limassol',sheet:'54',plan:'580601',block:null,parcel:945,price:263625,priceType:'Ελάχιστη τιμή πλειστηριασμού',sourceUrl:null,auctionDate:'2026-09-15'},
  AKI0002:{code:'ΕΡΓ-ΑΚΙ-0002',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'GoGordian 7281',registration:'4/115',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'47E1',block:4,parcel:117,registeredArea:17504,zone:'Ζ1',price:14400,priceType:'Τιμή πώλησης',sourceUrl:'https://gogordian.com/property/field-in-arsos--limassol-7281'},
  AKI0003:{code:'ΕΡΓ-ΑΚΙ-0003',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'REMU 42711',registration:'4/103',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'48W1',block:4,parcel:105,registeredArea:8569,zone:'Ζ1',price:21000,priceType:'Τιμή πώλησης',sourceUrl:null},
  AKI0004:{code:'ΕΡΓ-ΑΚΙ-0004',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'Altamira PR37313',registration:'4/97',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'40W1',block:5,parcel:99,registeredArea:13479,price:20000,priceType:'Ενδεικτική τιμή',sourceUrl:null},
  AKI0005:{code:'ΕΡΓ-ΑΚΙ-0005',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'Altamira PR44946',registration:null,district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',sheet:null,plan:null,block:null,parcel:null,price:null,priceType:'ΠΡΟΣ ΕΠΙΒΕΒΑΙΩΣΗ',sourceUrl:'https://www.altamirarealestate.com.cy/el/field-for-sale/agricultural/limassol/arsos/pr44946/132586/1',notes:'Ο cadastral locator και τα βασικά τεχνικά στοιχεία παραμένουν προς επιβεβαίωση.'},
  AKI0006:{code:'ΕΡΓ-ΑΚΙ-0006',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'GoGordian 8057',registration:'3/137',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'39E1',block:3,parcel:139,registeredArea:11096,zone:'Ζ1',price:20500,priceType:'Πρόσφατη τιμή — προς επανέλεγχο',sourceUrl:null,notes:'Υπήρχε παλαιότερη επίσημη τιμή €25.500.'},
  AKI0007:{code:'ΕΡΓ-ΑΚΙ-0007',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'REMU 40761',registration:'3/206',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'39E2',block:3,parcel:215,registeredArea:9297,zone:'Ζ1',price:19000,priceType:'Τιμή πώλησης',sourceUrl:null},
  AKI0008:{code:'ΕΡΓ-ΑΚΙ-0008',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ — ΠΛΕΙΣΤΗΡΙΑΣΜΟΣ',title:'Πλειστηριασμός 3/147',registration:'3/147',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'39E2',block:3,parcel:149,registeredArea:8384,price:10040,priceType:'Ελάχιστη τιμή πλειστηριασμού',sourceUrl:'https://www.moi.gov.cy/moi/auctions.nsf/43ABC3954847D09FC2258E4C00362416/$file/23-10-2026-%CE%9B%CE%95%CE%9C%CE%95%CE%A3%CE%9F%CE%A3-%CE%91%CE%A1%CE%A3%CE%9F%CE%A3%20%CE%9B%CE%95%CE%9C%CE%95%CE%A3%CE%9F%CE%A5-%CE%A7%CE%A9%CE%A1%CE%91%CE%A6%CE%99%203-147.pdf',auctionDate:'2026-10-23',auctionGuarantee:1004},
  AKI0009:{code:'ΕΡΓ-ΑΚΙ-0009',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'REMU 39724',registration:'3/141',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'39E1',block:3,parcel:143,registeredArea:18893,zone:'Ζ1',price:32000,priceType:'Τιμή πώλησης',sourceUrl:null},
  AKI0010:{code:'ΕΡΓ-ΑΚΙ-0010',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'Altamira PR45469',registration:'3/148',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'39E2',block:3,parcel:150,registeredArea:16444,zone:'Ζ1',price:26000,priceType:'Τιμή πώλησης',sourceUrl:null},
  AKI0011:{code:'ΕΡΓ-ΑΚΙ-0011',kind:'candidate',status:'ΜΕ ΕΝΔΙΑΦΕΡΕΙ',title:'Altamira PR39414',registration:'0/11974',district:'Λεμεσός',community:'Άρσος',areaKey:'arsos',vilCode:322,sheet:'46',plan:'40',block:0,parcel:702,registeredArea:1673,share:'2/5',zone:'Η2',price:18000,priceType:'Τιμή πώλησης',sourceUrl:null,notes:'Μερίδιο 2/5 — εμφανιζόμενο/αναλογούν εμβαδόν περίπου 669 m².'}
};

export const mapGroups={
  arsos:{title:'Άρσος — Ιδιόκτητα & προς αγορά',keys:Object.keys(properties).filter(k=>properties[k].areaKey==='arsos' && properties[k].sheet && properties[k].plan && properties[k].parcel!=null)},
  pafos:{title:'Άγιος Νικόλαος Πάφου — Ιδιόκτητα',keys:Object.keys(properties).filter(k=>properties[k].areaKey==='pafos' && properties[k].sheet && properties[k].plan && properties[k].parcel!=null)},
  ownedArsos:{title:'Άρσος — Ιδιόκτητα ακίνητα',keys:Object.keys(properties).filter(k=>properties[k].areaKey==='arsos'&&properties[k].kind==='owned'&&properties[k].sheet)},
  candidatesArsos:{title:'Άρσος — Ακίνητα προς αγορά',keys:Object.keys(properties).filter(k=>properties[k].areaKey==='arsos'&&properties[k].kind==='candidate'&&properties[k].sheet)}
};

export const areas={
  arsos:{district:'LEMESOS',communityNeedle:'ARSOS'},
  pafos:{district:'PAFOS',communityNeedle:'AGIOS NIKOLAOS'},
  limassol:{district:'LEMESOS',communityNeedle:'LEMESOS'},
  pentakomo:{district:'LEMESOS',communityNeedle:'PENTAKOMO'}
};
